Create requirements.txt
CodeForPoznan/alinka pull request #40
Opened 2018-10-05 13:30 UTC by Brzozova

2018-10-06 05:35 UTC, Rafalkufel requested changes
There should be rather python-docx== 0.8.7. Not python-docs-theme==2018.7

BTW I noticed that a new release came up in august this year.

2018-10-06 11:17 UTC, magul requested changes
This line should be changed and use `requirements.txt ` to install requirements.

More, in https://github.com/CodeForPoznan/alinka/commit/f87161f4ef57d71bbf7780331fe3abfd20132522 @Rafalkufel introduced tests and `nose` package. As it's only development tool it should be added to newly created `dev-requirements.txt` and also installed on AppVeyor` using `pip install -r dev-requirements.txt`

2018-10-06 11:59 UTC, Rafalkufel approved these changes

2025-05-27 17:21 UTC, magul commented
The pull request has been closed as part of preparations to archive the repository.

2025-05-27 17:21 UTC, closed without merging