Init filie
CodeForPoznan/alinka pull request #54
Opened 2018-10-10 17:00 UTC by Rafalkufel

Use `configParser` for create and read `alinka.ini`.

`alinka.ini` contains `[Center]` section which contains name of Support Center.

2018-10-12 14:06 UTC, magul requested changes

2018-10-12 14:06 UTC, magul commented on frontend/frames/settings.py
> +        if not sections:
this if does not make sense, as if `selection will be falsy, the whole `for` loop below will not run and `init = {}` will be returned (as here You have `return {}`).

More, if You have `return` in `if` statement the `else` clause doesn't make sense as these 2 sniipets will do exactly the same thing:
```
def f(a):
    if a:
        return 'a'
    else:
        return 'b'
```
and
```
def f(a):
    if a:
        return 'a'
    return 'b'
```

2018-10-12 14:06 UTC, magul commented on frontend/frames/settings.py
> +        config_dir = os.path.dirname(os.path.abspath(__name__))
3 first lines here and 3 first lines in `read_config` have a lot of common. Can we move them to one method?

2018-10-12 14:06 UTC, magul commented on frontend/frames/settings.py
> +        self.name.trace('w', self.track_changes)
I'm not a fun of having Tkinter and config file functionality in one class here. Can we create separate file for this `INI` file, that will expose object, that will return, save settings like geting, setting item in dictionary?

2018-10-12 14:06 UTC, magul commented on frontend/frames/settings.py
> +        self.name.trace('w', self.track_changes)
See:
https://docs.python.org/3.6/reference/datamodel.html#object.__getitem__
https://docs.python.org/3.6/reference/datamodel.html#object.__setitem__

2018-10-14 21:29 UTC, Rafalkufel commented on .gitignore
> +alinka.ini
Why not!

2025-05-27 17:20 UTC, magul commented
The pull request has been closed as part of preparations to archive the repository.

2025-05-27 17:20 UTC, closed without merging